# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-10-28 12:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fs4pso', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=20, verbose_name='유저 아이디')),
                ('user_pw', models.CharField(max_length=20, verbose_name='유저 비밀번호')),
                ('user_name', models.CharField(max_length=20, verbose_name='이름')),
                ('user_nickname', models.CharField(max_length=20, verbose_name='닉네임')),
                ('user_email', models.CharField(max_length=40, verbose_name='이메일')),
            ],
        ),
    ]
